# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "teuton-t-node-debian" do |i|
    i.vm.box = "debian/stretch64"
    i.vm.hostname = "t-node"
    i.vm.network "public_network"
#    i.vm.network :forwarded_port, guest: 22, host: 1600

    i.vm.provision "shell", inline: <<-SHELL
    wget -qO- https://raw.githubusercontent.com/dvarrui/teuton/master/bin/linux_t-node_install.sh | bash
  SHELL
    i.vm.provider "virtualbox" do |v|
      v.name = 'teuton-t-node-debian'
      v.memory = 2048
    end
  end
end
