# -*- mode: ruby -*-
# vi: set ft=ruby :

NAME = "teuton-s-node-debian"
BOX = "generic/debian11"
HOSTNAME = "snode-debian"

Vagrant.configure("2") do |config|
  config.vm.define NAME do |i|
    i.vm.box = BOX
    i.vm.hostname = HOSTANME
    i.vm.network "public_network"
    i.vm.network :forwarded_port, guest: 22, host: 2241
    i.vm.provision "shell", inline: <<-SHELL
    wget -qO- https://raw.githubusercontent.com/dvarrui/teuton/master/bin/linux_s-node_install.sh | bash
  SHELL
    i.vm.provider "virtualbox" do |v|
      v.name = NAME
      v.memory = 2048
    end
  end
end
