# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX = "generic/ubuntu2204"
HOSTNAME = "t-node"
VBNAME = "#{BOX.gsub("/", "_")}_#{HOSTNAME}"

Vagrant.configure("2") do |config|
  config.vm.define VBNAME do |i|
    i.vm.box = BOX
    i.vm.hostname = HOSTNAME
    i.vm.network "public_network", bridge: [ "wlp6s0" ]

    # i.vm.provision "shell", path: "install.sh"
    i.vm.provision "shell", inline: "gem install teuton"
    i.vm.provider "virtualbox" do |v|
      v.name = VBNAME
      v.memory = 2048
    end
  end
end
